### ISSUE TITLE
Allow a vector of column names to has_all_names

### ISSUE THREAD

**Issue by kdaily** [ropensci/assertr#75] opened 2018-09-05 22:29 UTC
This doesn't fail but doesn't work as expected:

```
d <- data.frame(a=1:3, b=4:6)
d %>% assertr::verify(assertr::has_all_names(c("a", "b", "c"))) # has no column "c" but passes
```

If I have a vector of column names, how can I use `has_all_names`? 

Thanks!

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 27 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
[1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
[4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
[7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] assertr_2.5

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.19   
```

**Comment by tonyfischetti** [comment] 2018-09-20 16:14
I'm sorry you had this problem.
The code actually works as intended. The function takes `...` an arbitrary amount of unquoted columns (the function documentation says this). For example:
```
d %>% verify(has_all_names("a", "b", "c"))
```
works, as does...
```
d %>% verify(do.call("has_all_names", as.list(c("a", "b", "c"))))
```
if you want to use a vector.

Do you think it would be helpful to include a wrapper function that can take a vector?

**Comment by tonyfischetti** [comment] 2018-09-20 16:36
After looking into it, I don't think it's a good idea to add this. The best way to do this in a principled manner is to use (eventually) `one_of` from the `tidyselect` package. This is a planned enhancement for sometime in the future.

In the meantime, if you don't mind, you can do something like this:
```
vec_conv <- function(fn, vec){ do.call(fn, as.list(vec)) }
d %>% verify(vec_conv(has_all_names, c("a", "b", "c")))
```

I'll close this issue for now (unless you have a big objection or someone wants to implement `tidyselect` integration now)

**Closed by tonyfischetti** 2018-09-20 16:36 UTC
